# Generated by Django 6.0.7 on 2026-07-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pageCount',
            field=models.IntegerField(null=True),
        ),
    ]
